### PR TITLE
Update monorepo.md

### PR DESCRIPTION
**Pull request by KarelVerschraegen**

### CODE REVIEW

**Review by goldbergyoni — DISMISSED** [review]
Keen eyes, great catch! Hope to see you here again

**Comment by goldbergyoni** [comment]
@all-contributors please add @KarelVerschraegen  for docs

**Comment by goldbergyoni** [comment]
@KarelVerschraegen This file has moved to /docs/docs/..., let's update in the new place, you or me, the first one to have few min to spare

**Comment by KarelVerschraegen** [comment]
You're welcome! I have resolved the merge conflicts.

**Review by goldbergyoni — APPROVED** [review]
Looks great 🛰🤗

**Comment by goldbergyoni** [comment]
@KarelVerschraegen Hope to see you here again, we're about to explore many fascinating and advanced backend topics

**Pull request merged**
