### PR TITLE
Feature/dynamic version

### PR DESCRIPTION
**Pull request by marcosmol204**
// TODO: Take this value from package.json

### CODE REVIEW

**Comment by goldbergyoni** [comment]
@marcosmol204 Awesome! 🛰 This can definitely save future mismatches, short and elegant

@all-contributors please add @marcosmol204  for code

**Comment by marcosmol204** [comment]
> @marcosmol204 Awesome! 🛰 This can definitely save future mismatches, short and elegant
> 
> @all-contributors please add @marcosmol204 for code

Thanks!
For this PR I need to add something?

**Comment by marcosmol204** [comment]
@goldbergyoni 
Thanks!
For this PR I need to add something?

**Comment by goldbergyoni** [comment]
@marcosmol204 No, I'm merging now. Congrats, your first PR here is inside the code 🤩

**Pull request merged**
