### PR TITLE
fix spelling and grammar in README

### PR DESCRIPTION
**Pull request by emilylubkert**

### CODE REVIEW

**Comment by goldbergyoni** [comment]
Howdy @emilylubkert  , welcome aboard ☀️ and many thanks for making this repo better 🙏

I was about to review but then noticed some conflicts with head, since you're more familiar with the nature of your change - See if you can resolve them quickly? If not, I'll do this in the next course of days

**Comment by emilylubkert** [comment]
Hi! Just resolved those conflicts and pushed another commit; let me know if I need to do anything else!

**Comment by goldbergyoni** [comment]
@emilylubkert There were 2 more conflicts which I fixed, for some reason can't see any grammar fix, can you point me toward one location that you changed? Many thanks

**Comment by rluvaton** [comment]
It seems like from the diff that the grammar mistakes were fixed, thanks anyway!

**Pull request closed without merging**
